// The onboarding pack's client: read what a worker group has of the pack,
// install it, upgrade it, remove it, and set the three things on its Raw HTTP
// source that only an install can know (port, auth token, TLS for the group's
// hosting), then commit and deploy the pack's files.
//
// ── WHY A MODULE OF ITS OWN, AND NOT pack.ts ────────────────────────────────
// pack.ts is PURE DATA on purpose: the query extractor loads it under plain
// Node, pack.test.ts parses the pack's YAML against it, and its header promises
// it "makes no network call and names no API path". Every export here does both.
// Putting them there would drag `capi`, the KV store and provision.ts into
// everything that only wants an id.
//
// ── NOTHING REACHES THIS YET, AND THE GATES KNOW IT ─────────────────────────
// Guided Setup's pack UI is a later slice. Until it lands, no module that
// `src/main.tsx` imports imports this one, so nothing on screen can call it.
// That is recorded, not assumed:
//   * src/cribl/paths.ts lists this file in `UNREACHED_MODULES`. The calls it
//     makes are named in `API_CALLS` like every other (so the source scan still
//     proves the list is complete), but `config/policies.yml` does NOT grant
//     them yet: a grant is asked of an admin for something a user can press.
//     policyCoverage.test.ts fails if one is declared early, and fails the
//     moment anything reachable from `src/main.tsx` imports this file while it
//     is still on that list — at which point the grants are due.
//   * src/cribl/authz.ts registers the writes under four `onboarding_pack.*`
//     WriteIds marked `unrendered`. gatedWrites.test.ts lets an unrendered id
//     go without a `<GatedControl>` only while every write it gates sits in an
//     unreached module, and fails once a control renders it with the marker
//     still on.
//
// ── WHAT EVERY WRITE HERE ASSUMES OF ITS CALLER ─────────────────────────────
// Each export that writes is an entry point reached from a confirmed click and
// from nowhere else (CLAUDE.md: nothing writes on load, render or a timer). The
// confirmation that names the pack, its version and the group lives with the
// UI; nothing in here can tell a deliberate click from an accidental one.
//
// ── SECRETS ─────────────────────────────────────────────────────────────────
// The Raw HTTP source's token is generated by the caller (provision.ts
// `generateToken`, 256 bits) and written into the pack's source ONLY. Nothing
// here returns it, logs it, puts it in a step or an error, or stores it: a
// failed PATCH's error is scrubbed of the new token and of every token the live
// source already held (`scrubbedErrText`), and `readPackState` reports whether a
// token is set, never what it is.
//
// ── NOT VERIFIED ON A LEADER (the proof install has to) ─────────────────────
//   * That a pack's sources answer at `/m/<g>/p/<pack>/system/inputs/<id>`, and
//     its routes, pipelines, outputs and breakers at the matching `/p/<pack>/…`
//     paths. openapi.json lists every one; no Leader in this project has a pack
//     with these objects installed.
//   * WHERE A PATCH OF A PACK SOURCE LANDS IN GIT. The pack's own files were
//     measured under `groups/<g>/default/<pack>/` and
//     `groups/<g>/data/packs/<pack>/`; an override of a pack source was not. The
//     commit therefore selects every pending path in the group with a
//     `/<pack>/` segment (`PACK_COMMIT_MARKERS`), which holds both measured
//     locations and any other directory named after the pack.
//   * That the release asset's bytes are the ones `PACK_SHA256` records. The
//     Leader downloads `PACK_URL` itself and `POST /packs` takes no digest, so
//     this app cannot check the hash; it refuses to install until one is
//     recorded (a release exists and was built by pack-release.yml), and checks
//     the version and an object afterwards. See `installRefusal`.

import { capi, groupPath } from './capi'
import { listDatasets } from './lake'
import {
  PACK_0_1_0,
  PACK_BREAKER_ID,
  PACK_HTTP_INPUT_ID,
  PACK_HTTP_JSON_ROUTE_ID,
  PACK_HTTP_PARQUET_ROUTE_ID,
  PACK_ID,
  PACK_JSON_OUTPUT_ID,
  PACK_PARQUET_OUTPUT_ID,
  PACK_PIPELINE_ID,
  PACK_PUBLISHED,
  PACK_SAMPLE_DATASET_ID,
  PACK_SAMPLE_INPUT_ID,
  PACK_SAMPLE_OUTPUT_ID,
  PACK_SAMPLE_ROUTE_ID,
  PACK_SHA256,
  PACK_URL,
  PACK_VERSION,
} from './pack'
import {
  SOURCE_SERVER_OWNED,
  commitMatchingAndDeploy,
  commitScopeFor,
  firstItem,
  groupInputs,
  portProblem,
  portsInUse,
  sameValue,
  scrubbedErrText,
  tlsFor,
  tokensOf,
  type CommitScope,
  type OnPhase,
  type ResourceState,
  type StepAction,
  type StepResult,
} from './provision'

/**
 * A path inside this pack, in a worker group: `/m/<group>/p/<PACK_ID><tail>`.
 *
 * policyCoverage.test.ts resolves a `packPath(group, …)` call site to
 * `/m/:gid/p/<PACK_ID>…` by name, the way it resolves `groupPath`; packClient's
 * own test holds this function to that reading.
 */
export const packPath = (group: string, tail: string): string => groupPath(group, `/p/${PACK_ID}${tail}`)

/** The versions of this pack this app published — the only ones it will
 *  upgrade from or remove. 0.1.0 is released; `PACK_VERSION` counts once its
 *  release exists. */
export const PUBLISHED_PACK_VERSIONS: readonly string[] = Object.freeze([
  PACK_0_1_0.version,
  ...(PACK_PUBLISHED && (PACK_VERSION as string) !== PACK_0_1_0.version ? [PACK_VERSION] : []),
])

/** How the picked worker group is hosted (provision.ts `hostingOf`); null is
 *  "cannot tell", and every write that depends on it refuses. */
export type Hosting = 'managed' | 'hybrid' | null

export type PackStepKey = 'pack' | 'http_input' | 'sample_input' | 'verify'

/** One thing a pack operation did, or refused to do. Never carries a token. */
export interface PackStep {
  key: PackStepKey
  action: StepAction
  detail?: string
}

// ── Reading ─────────────────────────────────────────────────────────────────

/** This pack as the group's pack list reports it. */
interface Installed {
  id: string
  version: string | null
}

/** The group's copy of this pack, `null` when it is not installed, or an error
 *  sentence when the list could not be read — which is never "not installed". */
async function readInstalled(group: string): Promise<{ pack: Installed | null } | { error: string }> {
  const r = await capi('GET', groupPath(group, '/packs'))
  if (r.status !== 200) return { error: `the group’s pack list could not be read (HTTP ${r.status})` }
  const list = (r.body as { items?: unknown })?.items
  if (!Array.isArray(list)) return { error: 'the group’s pack list came back in a shape this app cannot read' }
  const mine = list.find((p) => p && typeof p === 'object' && (p as { id?: unknown }).id === PACK_ID) as
    | { id: string; version?: unknown }
    | undefined
  if (!mine) return { pack: null }
  return { pack: { id: mine.id, version: typeof mine.version === 'string' && mine.version ? mine.version : null } }
}

/** `a` compared with `b` as dotted numbers: negative, zero or positive. A part
 *  that is not a number compares as 0, which only matters for a version this
 *  app did not publish — and those are refused before any comparison. */
export function compareVersions(a: string, b: string): number {
  const pa = a.split('.').map((x) => Number.parseInt(x, 10) || 0)
  const pb = b.split('.').map((x) => Number.parseInt(x, 10) || 0)
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0)
    if (d !== 0) return d
  }
  return 0
}

/** Every object the pack ships, by the kind of list it appears in. */
export const PACK_OBJECTS = Object.freeze({
  inputs: Object.freeze([PACK_HTTP_INPUT_ID, PACK_SAMPLE_INPUT_ID]),
  breakers: Object.freeze([PACK_BREAKER_ID]),
  pipelines: Object.freeze([PACK_PIPELINE_ID]),
  routes: Object.freeze([PACK_HTTP_JSON_ROUTE_ID, PACK_HTTP_PARQUET_ROUTE_ID, PACK_SAMPLE_ROUTE_ID]),
  outputs: Object.freeze([PACK_JSON_OUTPUT_ID, PACK_PARQUET_OUTPUT_ID, PACK_SAMPLE_OUTPUT_ID]),
})

export type PackObjectKind = keyof typeof PACK_OBJECTS

/** What the pack's Raw HTTP source says about itself. No token, only whether
 *  one is set. */
export interface HttpInputState {
  disabled: boolean
  port: number | null
  tokenSet: boolean
  tls: boolean
}

export interface PackState {
  /** Null when the pack list was read; otherwise why nothing below is known. */
  error: string | null
  installed: boolean
  version: string | null
  /** The installed version is one this app published (`PUBLISHED_PACK_VERSIONS`). */
  published: boolean
  /** The installed version is the one this build installs. */
  current: boolean
  /** Each shipped object, by kind and id. Empty when the pack is not installed. */
  objects: Record<PackObjectKind, Record<string, ResourceState>>
  http: HttpInputState | null
  sample: { disabled: boolean } | null
}

const emptyObjects = (): PackState['objects'] => ({ inputs: {}, breakers: {}, pipelines: {}, routes: {}, outputs: {} })

/** Ids in a `{items: [...]}` list, or null when the list could not be read. */
function idsOf(status: number, body: unknown): string[] | null {
  if (status !== 200) return null
  const list = (body as { items?: unknown })?.items
  if (!Array.isArray(list)) return null
  return list.map((x) => (x && typeof x === 'object' ? (x as { id?: unknown }).id : undefined)).filter((x): x is string => typeof x === 'string')
}

/** Route ids in a routing-table list: one table, its routes inside it. */
function routeIdsOf(status: number, body: unknown): string[] | null {
  if (status !== 200) return null
  const tables = (body as { items?: unknown })?.items
  if (!Array.isArray(tables)) return null
  return tables.flatMap((t) => {
    const routes = t && typeof t === 'object' ? (t as { routes?: unknown }).routes : undefined
    return Array.isArray(routes)
      ? routes.map((x) => (x && typeof x === 'object' ? ((x as { id?: unknown }).id ?? (x as { name?: unknown }).name) : undefined))
          .filter((x): x is string => typeof x === 'string')
      : []
  })
}

const stateIn = (ids: string[] | null, id: string): ResourceState => (ids === null ? 'unreadable' : ids.includes(id) ? 'present' : 'absent')

const numberOr = (v: unknown): number | null => {
  if (typeof v === 'number' && Number.isInteger(v)) return v
  if (typeof v === 'string' && /^\d+$/.test(v)) return Number(v)
  return null
}

/**
 * Whether the pack is installed in `group`, which version, which of its
 * objects are there, and what its two sources say. Every call is a GET.
 */
export async function readPackState(group: string): Promise<PackState> {
  const base: PackState = {
    error: null, installed: false, version: null, published: false, current: false,
    objects: emptyObjects(), http: null, sample: null,
  }
  const found = await readInstalled(group)
  if ('error' in found) return { ...base, error: found.error }
  if (!found.pack) return base
  const version = found.pack.version
  const state: PackState = {
    ...base,
    installed: true,
    version,
    published: version !== null && PUBLISHED_PACK_VERSIONS.includes(version),
    current: version === PACK_VERSION,
  }

  const [inputs, breaker, pipelines, routes, outputs] = await Promise.all([
    capi('GET', packPath(group, '/system/inputs')),
    capi('GET', packPath(group, `/lib/breakers/${PACK_BREAKER_ID}`)),
    capi('GET', packPath(group, '/pipelines')),
    capi('GET', packPath(group, '/routes')),
    capi('GET', packPath(group, '/system/outputs')),
  ])
  const inputIds = idsOf(inputs.status, inputs.body)
  for (const id of PACK_OBJECTS.inputs) state.objects.inputs[id] = stateIn(inputIds, id)
  state.objects.breakers[PACK_BREAKER_ID] =
    breaker.status === 200 ? 'present' : breaker.status === 404 ? 'absent' : 'unreadable'
  const pipelineIds = idsOf(pipelines.status, pipelines.body)
  for (const id of PACK_OBJECTS.pipelines) state.objects.pipelines[id] = stateIn(pipelineIds, id)
  const routeIds = routeIdsOf(routes.status, routes.body)
  for (const id of PACK_OBJECTS.routes) state.objects.routes[id] = stateIn(routeIds, id)
  const outputIds = idsOf(outputs.status, outputs.body)
  for (const id of PACK_OBJECTS.outputs) state.objects.outputs[id] = stateIn(outputIds, id)

  const list = inputs.status === 200 ? ((inputs.body as { items?: unknown })?.items as unknown[] | undefined) ?? [] : []
  const byId = (id: string) =>
    list.find((x) => x && typeof x === 'object' && (x as { id?: unknown }).id === id) as Record<string, unknown> | undefined
  const http = byId(PACK_HTTP_INPUT_ID)
  if (http) {
    const tls = http.tls && typeof http.tls === 'object' ? (http.tls as { disabled?: unknown }) : null
    state.http = {
      disabled: http.disabled === true,
      port: numberOr(http.port),
      tokenSet: tokensOf(http).length > 0,
      tls: tls !== null && tls.disabled === false,
    }
  }
  const sample = byId(PACK_SAMPLE_INPUT_ID)
  if (sample) state.sample = { disabled: sample.disabled === true }
  return state
}

// ── Installing, upgrading, removing ─────────────────────────────────────────

/**
 * Why this build may not install (or upgrade to) `PACK_VERSION`, or null when
 * it may.
 *
 * WHAT THIS GUARD IS, AND WHAT IT IS NOT. It refuses while no release of
 * `PACK_VERSION` exists (`PACK_PUBLISHED`) or while its digest is unrecorded
 * (`PACK_SHA256`): `PACK_URL` would be a 404, or would name bytes nobody wrote
 * down. It does NOT compare the downloaded bytes with `PACK_SHA256`, because it
 * never sees them — the Leader fetches `PACK_URL` itself and `POST /packs` has no
 * digest field. After an install the version and one known object are read
 * back (`verifyInstalled`).
 */
export function installRefusal(): string | null {
  if (!PACK_PUBLISHED) return `pack ${PACK_VERSION} has not been released, so there is nothing to install yet`
  if (!PACK_SHA256) return `pack ${PACK_VERSION} has no recorded sha256, so this app will not install it`
  return null
}

/** Read back what an install or upgrade left: the pack list says `version`,
 *  and the pack's Raw HTTP source exists. */
async function verifyInstalled(group: string, version: string): Promise<PackStep> {
  const found = await readInstalled(group)
  if ('error' in found) return { key: 'verify', action: 'error', detail: `could not check the install: ${found.error}` }
  if (!found.pack) return { key: 'verify', action: 'error', detail: `${PACK_ID} is not in the group’s pack list after the install` }
  if (found.pack.version !== version) {
    return { key: 'verify', action: 'error', detail: `${PACK_ID} reports version ${found.pack.version ?? 'none'}, not ${version}` }
  }
  const input = await capi('GET', packPath(group, `/system/inputs/${PACK_HTTP_INPUT_ID}`))
  if (input.status !== 200 || !firstItem(input)) {
    return { key: 'verify', action: 'error', detail: `${PACK_ID} ${version} is installed, but its source ${PACK_HTTP_INPUT_ID} could not be read (HTTP ${input.status})` }
  }
  return { key: 'verify', action: 'exists', detail: `${PACK_ID} ${version} · ${PACK_HTTP_INPUT_ID} present` }
}

/** Install `PACK_VERSION` from `PACK_URL` into `group`, then read it back.
 *  Refuses when the pack is already there: that is `upgradePack`'s job. */
export async function installPack(group: string): Promise<PackStep[]> {
  const refusal = installRefusal()
  if (refusal) return [{ key: 'pack', action: 'skipped', detail: refusal }]
  const found = await readInstalled(group)
  if ('error' in found) return [{ key: 'pack', action: 'error', detail: found.error }]
  if (found.pack) {
    const at = found.pack.version ? ` ${found.pack.version}` : ''
    return [{ key: 'pack', action: 'error', detail: `${PACK_ID}${at} is already installed in ${group} — upgrade it instead` }]
  }
  const r = await capi('POST', groupPath(group, '/packs'), { id: PACK_ID, source: PACK_URL, allowCustomFunctions: false })
  if (r.status < 200 || r.status >= 300) return [{ key: 'pack', action: 'error', detail: scrubbedErrText(r, []) }]
  return [{ key: 'pack', action: 'created', detail: `${PACK_ID} ${PACK_VERSION}` }, await verifyInstalled(group, PACK_VERSION)]
}

/**
 * Upgrade an installed copy to `PACK_VERSION` in place (`PATCH /packs/<id>
 * {source}`, measured). Only from a version this app published, and never
 * down: a newer copy than this build knows is left as it is.
 */
export async function upgradePack(group: string): Promise<PackStep[]> {
  const refusal = installRefusal()
  if (refusal) return [{ key: 'pack', action: 'skipped', detail: refusal }]
  const found = await readInstalled(group)
  if ('error' in found) return [{ key: 'pack', action: 'error', detail: found.error }]
  if (!found.pack) return [{ key: 'pack', action: 'error', detail: `${PACK_ID} is not installed in ${group} — install it instead` }]
  const from = found.pack.version
  if (from === null || !PUBLISHED_PACK_VERSIONS.includes(from)) {
    return [{ key: 'pack', action: 'error', detail: `kept — the installed ${PACK_ID} is version ${from ?? 'unknown'}, which this app did not publish` }]
  }
  if (from === PACK_VERSION) return [{ key: 'pack', action: 'exists', detail: `${PACK_ID} is already ${PACK_VERSION}` }]
  if (compareVersions(from, PACK_VERSION) > 0) {
    return [{ key: 'pack', action: 'error', detail: `kept — the installed ${from} is newer than the ${PACK_VERSION} this app installs` }]
  }
  const r = await capi('PATCH', groupPath(group, `/packs/${PACK_ID}`), { source: PACK_URL, allowCustomFunctions: false })
  if (r.status < 200 || r.status >= 300) return [{ key: 'pack', action: 'error', detail: scrubbedErrText(r, []) }]
  return [{ key: 'pack', action: 'updated', detail: `${PACK_ID} ${from} → ${PACK_VERSION}` }, await verifyInstalled(group, PACK_VERSION)]
}

/**
 * Uninstall the pack — only when the installed pack's id is this app's and its
 * version is one this app published. The Lake datasets it writes to are outside
 * the pack and are left alone.
 */
export async function removePack(group: string): Promise<PackStep> {
  const found = await readInstalled(group)
  if ('error' in found) return { key: 'pack', action: 'error', detail: `kept — ${found.error}` }
  if (!found.pack) return { key: 'pack', action: 'exists', detail: 'not present' }
  if (found.pack.id !== PACK_ID) return { key: 'pack', action: 'error', detail: 'kept — the installed pack is not this app’s' }
  const version = found.pack.version
  if (version === null || !PUBLISHED_PACK_VERSIONS.includes(version)) {
    return { key: 'pack', action: 'error', detail: `kept — the installed ${PACK_ID} is version ${version ?? 'unknown'}, which this app did not publish` }
  }
  const r = await capi('DELETE', groupPath(group, `/packs/${PACK_ID}`))
  if (r.status === 404) return { key: 'pack', action: 'exists', detail: 'not present' }
  if (r.status < 200 || r.status >= 300) return { key: 'pack', action: 'error', detail: scrubbedErrText(r, []) }
  return { key: 'pack', action: 'updated', detail: 'deleted' }
}

// ── The pack's two sources ──────────────────────────────────────────────────

type Which = 'http' | 'sample'

/** What an edit of a live source decided: the keys to set, or why not. */
type Edit = { set: Record<string, unknown> } | { refuse: string }

const inputKey = (which: Which): PackStepKey => (which === 'http' ? 'http_input' : 'sample_input')

/**
 * GET → overlay → PATCH the whole body of one of the pack's sources. The
 * endpoint is a full replacement (openapi.json, and measured on the group's own
 * sources), so the body is the live object with only `edit`'s keys changed and
 * the server-owned keys left out. Nothing is sent when every key already says
 * what `edit` wants. `secrets` are scrubbed from any error, beside every token
 * the live source already holds.
 */
async function patchPackInput(
  group: string,
  which: Which,
  edit: (live: Record<string, unknown>) => Edit,
  secrets: readonly string[] = [],
): Promise<PackStep> {
  const key = inputKey(which)
  const id = which === 'http' ? PACK_HTTP_INPUT_ID : PACK_SAMPLE_INPUT_ID
  const got = which === 'http'
    ? await capi('GET', packPath(group, `/system/inputs/${PACK_HTTP_INPUT_ID}`))
    : await capi('GET', packPath(group, `/system/inputs/${PACK_SAMPLE_INPUT_ID}`))
  if (got.status === 404) return { key, action: 'error', detail: `${id} is not in ${PACK_ID} here — is the pack installed?` }
  const live = got.status === 200 ? firstItem(got) : null
  if (!live) {
    return {
      key, action: 'error',
      detail: got.status === 200
        ? `not applied — this app could not read the live ${id}, and this endpoint replaces the whole object`
        : scrubbedErrText(got, secrets),
    }
  }
  const scrub = [...tokensOf(live), ...secrets]
  const decided = edit(live)
  if ('refuse' in decided) return { key, action: 'error', detail: decided.refuse }
  if (Object.entries(decided.set).every(([k, v]) => sameValue(live[k], v))) {
    return { key, action: 'exists', detail: 'already set' }
  }
  const body: Record<string, unknown> = { ...live }
  for (const k of SOURCE_SERVER_OWNED) delete body[k]
  Object.assign(body, decided.set)
  const r = which === 'http'
    ? await capi('PATCH', packPath(group, `/system/inputs/${PACK_HTTP_INPUT_ID}`), body)
    : await capi('PATCH', packPath(group, `/system/inputs/${PACK_SAMPLE_INPUT_ID}`), body)
  if (r.status < 200 || r.status >= 300) return { key, action: 'error', detail: scrubbedErrText(r, scrub) }
  return { key, action: 'updated', detail: Object.keys(decided.set).sort().join(', ') }
}

/** The ports every other source in the group listens on — its own, and other
 *  packs' — or null when any could not be read ("cannot tell" is never "free"). */
async function portsOfOthers(group: string): Promise<number[] | null> {
  const inputs = await groupInputs(group)
  if (!inputs) return null
  return portsInUse(inputs.filter((i) => !(i.pack === PACK_ID && i.id === PACK_HTTP_INPUT_ID)))
}

/** A token this app would have generated: at least 128 bits, as hex. The
 *  refusal never repeats what it was given. */
const TOKEN_SHAPE = /^[0-9a-f]{32,}$/i
const BAD_TOKEN = 'not applied — the token must be at least 128 bits of hex, as generateToken makes it'
const NO_HOSTING = 'not applied — this app cannot tell whether the group is Cribl-managed or hybrid, which decides the port range and TLS'

/** Why an enabled source here would be unsafe, or null. */
function enableProblem(live: Record<string, unknown>, hosting: 'managed' | 'hybrid', used: number[] | null): string | null {
  if (tokensOf(live).length === 0) {
    return 'not enabled — the source has no auth token, so it would accept a POST from anyone who can reach the port'
  }
  const port = numberOr(live.port)
  if (port === null) return 'not enabled — this app cannot read the source’s port'
  const problem = portProblem(port, hosting === 'managed', used)
  return problem ? `not enabled — port ${port}: ${problem}` : null
}

/**
 * Everything an install has to set on the pack's Raw HTTP source, in ONE
 * whole-body PATCH: a free port for the group's hosting, the new token, TLS on
 * Cribl's certificate on a managed group (off on a hybrid one), and enabled.
 * This is the call the Guided Setup slice makes after an install.
 */
export async function configureHttpInput(
  group: string,
  opts: { port: number; token: string; hosting: Hosting },
): Promise<PackStep> {
  if (!opts.hosting) return { key: 'http_input', action: 'error', detail: NO_HOSTING }
  if (!TOKEN_SHAPE.test(opts.token)) return { key: 'http_input', action: 'error', detail: BAD_TOKEN }
  const managed = opts.hosting === 'managed'
  const used = await portsOfOthers(group)
  const problem = portProblem(opts.port, managed, used)
  if (problem) return { key: 'http_input', action: 'error', detail: `not applied — port ${opts.port}: ${problem}` }
  return patchPackInput(group, 'http', () => ({
    set: {
      port: opts.port,
      tls: tlsFor(managed),
      authTokensExt: [{ token: opts.token, authType: 'manual' }],
      disabled: false,
    },
  }), [opts.token])
}

/** Move the pack's Raw HTTP source to another port, checked free and inside
 *  what the group's hosting allows. */
export async function setSourcePort(group: string, port: number, hosting: Hosting): Promise<PackStep> {
  if (!hosting) return { key: 'http_input', action: 'error', detail: NO_HOSTING }
  const problem = portProblem(port, hosting === 'managed', await portsOfOthers(group))
  if (problem) return { key: 'http_input', action: 'error', detail: `not applied — port ${port}: ${problem}` }
  return patchPackInput(group, 'http', () => ({ set: { port } }))
}

/** Replace the pack's Raw HTTP source's auth token (a rotation). The old one
 *  stops working at the next deploy. */
export async function setHttpToken(group: string, token: string): Promise<PackStep> {
  if (!TOKEN_SHAPE.test(token)) return { key: 'http_input', action: 'error', detail: BAD_TOKEN }
  return patchPackInput(group, 'http', () => ({ set: { authTokensExt: [{ token, authType: 'manual' }] } }), [token])
}

/** Start the pack's Raw HTTP source, with TLS for the group's hosting. Refused
 *  while it has no token or its port is not usable. */
export async function enableHttpInput(group: string, hosting: Hosting): Promise<PackStep> {
  if (!hosting) return { key: 'http_input', action: 'error', detail: NO_HOSTING }
  const used = await portsOfOthers(group)
  return patchPackInput(group, 'http', (live) => {
    const problem = enableProblem(live, hosting, used)
    return problem ? { refuse: problem } : { set: { disabled: false, tls: tlsFor(hosting === 'managed') } }
  })
}

/**
 * Start or stop the sample DataGen. Starting it is refused until its own
 * dataset, `gigamon_ami_sample`, exists: the pack cannot create a dataset, and
 * a destination with nowhere to write blocks.
 */
export async function setSampleEnabled(group: string, enabled: boolean): Promise<PackStep> {
  if (enabled) {
    const datasets = await listDatasets()
    if (datasets.outcome !== 'ok') {
      return { key: 'sample_input', action: 'error', detail: `not started — Cribl Lake’s dataset list could not be read, so this app cannot check ${PACK_SAMPLE_DATASET_ID} exists` }
    }
    if (!(datasets.value ?? []).some((d) => d.id === PACK_SAMPLE_DATASET_ID)) {
      return { key: 'sample_input', action: 'error', detail: `not started — the ${PACK_SAMPLE_DATASET_ID} dataset does not exist yet` }
    }
  }
  return patchPackInput(group, 'sample', () => ({ set: { disabled: !enabled } }))
}

// ── Committing the pack's files ─────────────────────────────────────────────

/**
 * What selects this pack's files among a group's pending Git paths: any path
 * with a segment named exactly after the pack. MEASURED: an install lands
 * under `groups/<g>/default/<pack>/` and `groups/<g>/data/packs/<pack>/`; both
 * hold this segment, and so would any other directory Cribl names after the
 * pack (where a PATCH of a pack source lands is not measured). A sibling pack
 * whose id merely starts with this one's does not match: the segment is
 * slash-delimited on both sides.
 */
export const PACK_COMMIT_MARKERS: readonly string[] = Object.freeze([`/${PACK_ID}/`])

/** The two measured directories, as the commit names them when Git reports
 *  nothing pending at all (provision.ts's fallback). */
export const packCommitPaths = (group: string): string[] => [
  `groups/${group}/default/${PACK_ID}`,
  `groups/${group}/data/packs/${PACK_ID}`,
]

/** What a commit of the pack's files in `group` carries, and what else is
 *  pending — the two things its confirmation has to say (provision.ts
 *  `commitScopeFor`). Pure: `pending` is `pendingConfigPaths()`. */
export function packCommitScope(group: string, pending: readonly string[] | null): CommitScope {
  return commitScopeFor(group, packCommitPaths(group), PACK_COMMIT_MARKERS, pending)
}

/** Commit exactly the pack's pending files in `group`, then deploy — Guided
 *  Setup's own machinery (provision.ts `commitMatchingAndDeploy`), not a copy. */
export async function commitAndDeployPack(
  group: string,
  message: string,
  onStep?: (r: StepResult) => void,
  onPhase?: OnPhase,
): Promise<StepResult[]> {
  return commitMatchingAndDeploy(message, group, PACK_COMMIT_MARKERS, packCommitPaths(group), onStep, onPhase)
}
