// The onboarding pack's client: read what a worker group has of the pack,
// install it, upgrade it, remove it, and set the three things on its Raw HTTP
// source that only an install can know (port, auth token, TLS for the group's
// hosting), then commit and deploy the pack's files.
//
// ── WHY A MODULE OF ITS OWN, AND NOT pack.ts ────────────────────────────────
// pack.ts is PURE DATA on purpose: the query extractor loads it under plain
// Node, pack.test.ts parses the pack's YAML against it, and its header promises
// it "makes no network call and names no API path". Every export here does both.
// Putting them there would drag `capi`, the KV store and provision.ts into
// everything that only wants an id.
//
// ── WHO REACHES THIS, AND WHAT THAT COST ────────────────────────────────────
// Guided Setup's onboarding panel (components/OnboardingPanel.tsx) and its run
// (cribl/onboarding/run.ts) import this module, so every call here is reachable
// from `src/main.tsx` and is GRANTED in `config/policies.yml` — each pack path
// named with exactly the methods called on it, and no `*` (policyCoverage
// .test.ts holds both directions). Its writes are registered in
// src/cribl/authz.ts under `onboarding_pack.install`, `.configure` and
// `.remove` (and the upgrade's under `.upgrade`), each rendered by a
// `<GatedControl>` on that panel. *(Until 2026-09-24 this
// module was on paths.ts `UNREACHED_MODULES`, built a slice ahead of its UI,
// with its grants deliberately withheld.)*
//
// The in-place upgrade is NOT here: it is packUpgrade.ts, split out so that its
// PATCH was not granted before a control could send it. Upgrade is offered now
// (onboarding/run.ts `runPackUpgrade`, which reads the Raw HTTP source back),
// so that module is reached and its PATCH granted. The pack sources' own
// settings outside an onboarding run — rotate the token (`setHttpToken`), move
// the port (`setSourcePort`), start or stop the sample (`setSampleEnabled`) —
// are offered too, each gated by `onboarding_pack.configure`. *(Corrected
// 2026-09-24, `feat/pack-onboarding-slice3`: this said neither had a control,
// and that their WriteId was withdrawn. On `feat/pack-onboarding-4a`,
// `upgradePack` lived here, so its PATCH was granted for a control that
// rendered refused and could never send it.)*
//
// ── WHAT EVERY WRITE HERE ASSUMES OF ITS CALLER ─────────────────────────────
// Each export that writes is an entry point reached from a confirmed click and
// from nowhere else (CLAUDE.md: nothing writes on load, render or a timer). The
// confirmation that names the pack, its version and the group lives with the
// UI; nothing in here can tell a deliberate click from an accidental one.
//
// WHAT THE UI SLICE HAS TO WIRE, because nothing here can do it for it:
//   * A source change is previewed before it is confirmed: `previewPackInput`
//     returns the before→after (`DiffRow[]`, token values masked) for
//     `<ConfirmDialog diff>`, with GETs only. Pass the diff the person approved
//     to `applyPackInput` (or a named wrapper's `approved`), which refuses and
//     sends nothing when the live source no longer gives that same diff.
//   * `commitAndDeployPack` requires `record`: ProvisionPanel's `recordCommit`,
//     bound to the group and `PACK_COMMIT_KEY`. The stranded-commit repair
//     deploys only a hash in that memory, so an unrecorded pack commit whose
//     deploy failed could never be deployed by this app again. It also requires
//     `wrote`, whether this run's pack write changed anything, because after a
//     change "nothing to commit" is an error, not "up to date".
//   * `readPackState().current` already requires a released version installed
//     from its release; do not re-derive "up to date" from `version`.
//
// ── OWNERSHIP: TWO SIGNALS, AS ACCELERATION'S TEARDOWN HAS ───────────────────
// A copy is this app's only when (1) its version is on `PUBLISHED_PACK_VERSIONS`
// AND (2) the group's pack list names that version's release asset
// (`packReleaseUrl`) as its `source`. The id alone proves nothing — the pack
// list is looked up by it — and a version string is only a string: a same-id
// fork, or a dev build that says 0.1.0, carries both. Remove and Upgrade refuse
// anything that fails either, and say which.
//
// ── SECRETS ─────────────────────────────────────────────────────────────────
// The Raw HTTP source's token is generated by the caller (provision.ts
// `generateToken`, 256 bits) and written into the pack's source ONLY. Nothing
// here returns it, logs it, puts it in a step, a diff or an error, or stores it:
// a failed PATCH's error is scrubbed of the new token and of every token the
// live source already held (`scrubbedErrText`), a diff shows "a new token (not
// shown)", and `readPackState` reports whether a token is set, never what it is.
//
// ── NOT VERIFIED ON A LEADER (the proof install has to) ─────────────────────
//   * That a pack's sources answer at `/m/<g>/p/<pack>/system/inputs/<id>`, and
//     its routes, pipelines, outputs and breakers at the matching `/p/<pack>/…`
//     paths. openapi.json lists every one; no Leader in this project has a pack
//     with these objects installed.
//   * WHERE A PATCH OF A PACK SOURCE LANDS IN GIT. The pack's own files were
//     measured under `groups/<g>/default/<pack>/` and
//     `groups/<g>/data/packs/<pack>/`; an override of a pack source was not. The
//     commit therefore selects every pending path in the group with a
//     `/<pack>/` segment (`PACK_COMMIT_MARKERS`), which holds both measured
//     locations and any other directory named after the pack. Nor is it
//     measured how Git status names a NEW, untracked pack directory: without a
//     trailing slash (`…/default/<pack>`) the marker misses it. Either way the
//     pack flow does not report success: after a write, nothing to commit is an
//     error (`commitAndDeployPack`).
//   * That the pack list's `source` for a copy installed from `PACK_URL` is
//     `PACK_URL` itself, and that an in-place upgrade moves it to the new URL.
//     openapi.json's PackInfo requires `source` ("a file path, URL, or Git URL
//     from which the Pack was installed") and its URL-install and upgrade
//     examples show exactly that, but no install on a Leader here was read back
//     for it. If it is anything else, this fails CLOSED: `verifyInstalled`
//     reports the install as unverified, and Remove and Upgrade keep the copy.
//   * That `PATCH /packs/<id>` accepts `allowCustomFunctions: false`. Only
//     `{source}` was sent on a Leader. openapi.json's PackUpgradeRequest lists
//     the field and says an OMITTED one ALLOWS custom JavaScript functions, so
//     it is sent; a Leader that answers 400 fails the upgrade loudly, with
//     nothing changed.
//   * That the release asset's bytes are the ones `PACK_SHA256` records. The
//     Leader downloads `PACK_URL` itself and `POST /packs` takes no digest, so
//     this app cannot check the hash; it refuses to install until one is
//     recorded (a release exists and was built by pack-release.yml), and checks
//     the version, the source and an object afterwards. See `installRefusal`.

import { capi, groupPath } from './capi'
import { listDatasets } from './lake'
import { sameDiff, type DiffRow } from './landing'
import {
  PACK_BREAKER_ID,
  PACK_HTTP_INPUT_ID,
  PACK_ID,
  PACK_OBJECTS,
  type PackObjectKind,
  PACK_PUBLISHED,
  PACK_PUBLISHED_VERSIONS,
  PACK_SAMPLE_DATASET_ID,
  PACK_SAMPLE_INPUT_ID,
  PACK_SHA256,
  PACK_URL,
  PACK_VERSION,
  packRelease,
  packReleaseUrl,
  type PackRelease,
} from './pack'
import {
  SOURCE_SERVER_OWNED,
  commitMatchingAndDeploy,
  commitScopeFor,
  firstItem,
  groupInputs,
  portProblem,
  portsInUse,
  sameValue,
  scrubbedErrText,
  tlsFor,
  tokensOf,
  type CommitScope,
  type OnPhase,
  type ResourceState,
  type StepAction,
  type StepResult,
} from './provision'

/**
 * A path inside this pack, in a worker group: `/m/<group>/p/<PACK_ID><tail>`.
 *
 * policyCoverage.test.ts resolves a `packPath(group, …)` call site to
 * `/m/:gid/p/<PACK_ID>…` by name, the way it resolves `groupPath`; packClient's
 * own test holds this function to that reading.
 */
export const packPath = (group: string, tail: string): string => groupPath(group, `/p/${PACK_ID}${tail}`)

/** The versions of this pack this app published — the only ones it will
 *  upgrade from or remove. pack.ts's hand-kept, append-only list: it is NOT
 *  derived from `PACK_VERSION`, so moving that on never drops the release
 *  before it. */
export const PUBLISHED_PACK_VERSIONS: readonly string[] = PACK_PUBLISHED_VERSIONS

/** How the picked worker group is hosted (provision.ts `hostingOf`); null is
 *  "cannot tell", and every write that depends on it refuses. */
export type Hosting = 'managed' | 'hybrid' | null

export type PackStepKey = 'pack' | 'http_input' | 'sample_input' | 'verify'

/** One thing a pack operation did, or refused to do. Never carries a token. */
export interface PackStep {
  key: PackStepKey
  action: StepAction
  detail?: string
  /**
   * Set on an `error` that the write itself answered — the request WAS sent —
   * so a caller can tell it from a refusal that sent nothing. The onboarding
   * run re-reads the source only then: a token may have landed although the
   * answer was an error, and a refusal cannot have put one there.
   */
  sent?: boolean
}

// ── Reading ─────────────────────────────────────────────────────────────────

/** This pack as the group's pack list reports it. */
export interface Installed {
  version: string | null
  /** Where Cribl says the copy was installed from (PackInfo `source`). */
  source: string | null
}

/** The group's copy of this pack, `null` when it is not installed, or an error
 *  sentence when the list could not be read — which is never "not installed".
 *  Exported for packUpgrade.ts, which holds the in-place upgrade. */
export async function readInstalled(group: string): Promise<{ pack: Installed | null } | { error: string }> {
  const r = await capi('GET', groupPath(group, '/packs'))
  if (r.status !== 200) return { error: `the group’s pack list could not be read (HTTP ${r.status})` }
  const list = (r.body as { items?: unknown })?.items
  if (!Array.isArray(list)) return { error: 'the group’s pack list came back in a shape this app cannot read' }
  const mine = list.find((p) => p && typeof p === 'object' && (p as { id?: unknown }).id === PACK_ID) as
    | { version?: unknown; source?: unknown }
    | undefined
  if (!mine) return { pack: null }
  const text = (v: unknown) => (typeof v === 'string' && v ? v : null)
  return { pack: { version: text(mine.version), source: text(mine.source) } }
}

/** The two ownership signals, each on its own (see the header). */
function ownership(p: Installed): { published: boolean; fromRelease: boolean } {
  const v = p.version
  return {
    published: v !== null && PUBLISHED_PACK_VERSIONS.includes(v),
    fromRelease: v !== null && p.source === packReleaseUrl(v),
  }
}

/** Why the installed copy is not this app's to upgrade or remove, or null. The
 *  install source is never repeated: a Git URL can carry credentials. Exported
 *  for packUpgrade.ts. */
export function notOurs(p: Installed): string | null {
  const { published, fromRelease } = ownership(p)
  if (!published) return `kept — the installed ${PACK_ID} is version ${p.version ?? 'unknown'}, which this app did not publish`
  if (!fromRelease) {
    return `kept — the installed ${PACK_ID} ${p.version} was not installed from this app’s release of that version ` +
      `(the group’s pack list names ${p.source ? 'another source' : 'no source'}), so this app does not treat it as its own`
  }
  return null
}

/** `a` compared with `b` as dotted numbers: negative, zero or positive. A part
 *  that is not a number compares as 0, which only matters for a version this
 *  app did not publish — and those are refused before any comparison. */
export function compareVersions(a: string, b: string): number {
  const pa = a.split('.').map((x) => Number.parseInt(x, 10) || 0)
  const pb = b.split('.').map((x) => Number.parseInt(x, 10) || 0)
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0)
    if (d !== 0) return d
  }
  return 0
}

/** Every object the pack ships, by the kind of list it appears in. pack.ts's,
 *  re-exported: the onboarding plan names them too, and must not import this
 *  module (see its header). */
export { PACK_OBJECTS, type PackObjectKind }

/** What the pack's Raw HTTP source says about itself. No token, only whether
 *  one is set. */
export interface HttpInputState {
  disabled: boolean
  port: number | null
  tokenSet: boolean
  tls: boolean
  /**
   * Which certificate TLS uses, while it is on: the block's certificate name
   * and its cert, key and CA paths, joined — never its passphrase. Null when
   * TLS is off. An upgrade that puts a group's own certificate back to the
   * pack's shipped one leaves `tls` true, and only this shows the change.
   */
  tlsCert: string | null
}

/** The TLS block's certificate, as `HttpInputState.tlsCert` names it. */
function tlsCertOf(tls: Record<string, unknown>): string {
  const text = (v: unknown) => (typeof v === 'string' ? v : '')
  return [tls.certificateName, tls.certPath, tls.privKeyPath, tls.caPath].map(text).join(' ').trim()
}

export interface PackState {
  /** Null when the pack list was read; otherwise why nothing below is known. */
  error: string | null
  installed: boolean
  version: string | null
  /** The installed version is one this app published (`PUBLISHED_PACK_VERSIONS`). */
  published: boolean
  /** The pack list names that version's release asset as where the copy came
   *  from — the second ownership signal. Remove and Upgrade need both. */
  fromRelease: boolean
  /**
   * The installed copy is THIS BUILD'S RELEASED VERSION, installed from its
   * release: `version === PACK_VERSION` and `published` and `fromRelease`. An
   * unreleased PACK_VERSION (a dev build, or this build before its release) is not
   * current, so it can never be shown as up to date.
   */
  current: boolean
  /** Each shipped object, by kind and id. Empty when the pack is not installed. */
  objects: Record<PackObjectKind, Record<string, ResourceState>>
  http: HttpInputState | null
  sample: { disabled: boolean } | null
}

const emptyObjects = (): PackState['objects'] => ({ inputs: {}, breakers: {}, pipelines: {}, routes: {}, outputs: {} })

/** Ids in a `{items: [...]}` list, or null when the list could not be read. */
function idsOf(status: number, body: unknown): string[] | null {
  if (status !== 200) return null
  const list = (body as { items?: unknown })?.items
  if (!Array.isArray(list)) return null
  return list.map((x) => (x && typeof x === 'object' ? (x as { id?: unknown }).id : undefined)).filter((x): x is string => typeof x === 'string')
}

/** Route ids in a routing-table list: one table, its routes inside it. */
function routeIdsOf(status: number, body: unknown): string[] | null {
  if (status !== 200) return null
  const tables = (body as { items?: unknown })?.items
  if (!Array.isArray(tables)) return null
  return tables.flatMap((t) => {
    const routes = t && typeof t === 'object' ? (t as { routes?: unknown }).routes : undefined
    return Array.isArray(routes)
      ? routes.map((x) => (x && typeof x === 'object' ? ((x as { id?: unknown }).id ?? (x as { name?: unknown }).name) : undefined))
          .filter((x): x is string => typeof x === 'string')
      : []
  })
}

const stateIn = (ids: string[] | null, id: string): ResourceState => (ids === null ? 'unreadable' : ids.includes(id) ? 'present' : 'absent')

const numberOr = (v: unknown): number | null => {
  if (typeof v === 'number' && Number.isInteger(v)) return v
  if (typeof v === 'string' && /^\d+$/.test(v)) return Number(v)
  return null
}

/**
 * Whether the pack is installed in `group`, which version, whether it is this
 * app's, which of its objects are there, and what its two sources say. Every
 * call is a GET.
 */
export async function readPackState(group: string): Promise<PackState> {
  const base: PackState = {
    error: null, installed: false, version: null, published: false, fromRelease: false, current: false,
    objects: emptyObjects(), http: null, sample: null,
  }
  const found = await readInstalled(group)
  if ('error' in found) return { ...base, error: found.error }
  if (!found.pack) return base
  const version = found.pack.version
  const { published, fromRelease } = ownership(found.pack)
  const state: PackState = {
    ...base,
    installed: true,
    version,
    published,
    fromRelease,
    current: version === PACK_VERSION && published && fromRelease,
  }

  const [inputs, breaker, pipelines, routes, outputs] = await Promise.all([
    capi('GET', packPath(group, '/system/inputs')),
    capi('GET', packPath(group, `/lib/breakers/${PACK_BREAKER_ID}`)),
    capi('GET', packPath(group, '/pipelines')),
    capi('GET', packPath(group, '/routes')),
    capi('GET', packPath(group, '/system/outputs')),
  ])
  const inputIds = idsOf(inputs.status, inputs.body)
  for (const id of PACK_OBJECTS.inputs) state.objects.inputs[id] = stateIn(inputIds, id)
  state.objects.breakers[PACK_BREAKER_ID] =
    breaker.status === 200 ? 'present' : breaker.status === 404 ? 'absent' : 'unreadable'
  const pipelineIds = idsOf(pipelines.status, pipelines.body)
  for (const id of PACK_OBJECTS.pipelines) state.objects.pipelines[id] = stateIn(pipelineIds, id)
  const routeIds = routeIdsOf(routes.status, routes.body)
  for (const id of PACK_OBJECTS.routes) state.objects.routes[id] = stateIn(routeIds, id)
  const outputIds = idsOf(outputs.status, outputs.body)
  for (const id of PACK_OBJECTS.outputs) state.objects.outputs[id] = stateIn(outputIds, id)

  const list = inputs.status === 200 ? ((inputs.body as { items?: unknown })?.items as unknown[] | undefined) ?? [] : []
  const byId = (id: string) =>
    list.find((x) => x && typeof x === 'object' && (x as { id?: unknown }).id === id) as Record<string, unknown> | undefined
  const http = byId(PACK_HTTP_INPUT_ID)
  if (http) {
    const tls = http.tls && typeof http.tls === 'object' ? (http.tls as Record<string, unknown>) : null
    const tlsOn = tls !== null && tls.disabled === false
    state.http = {
      disabled: http.disabled === true,
      port: numberOr(http.port),
      tokenSet: tokensOf(http).length > 0,
      tls: tlsOn,
      tlsCert: tlsOn && tls ? tlsCertOf(tls) : null,
    }
  }
  const sample = byId(PACK_SAMPLE_INPUT_ID)
  if (sample) state.sample = { disabled: sample.disabled === true }
  return state
}

// ── Installing, upgrading, removing ─────────────────────────────────────────

/**
 * Why this build may not install (or upgrade to) `PACK_VERSION`, or null when
 * it may. pack.ts's `packRelease`, bound to the three constants this module
 * imports — the logic and its sentences live there, pure, so the Guided Setup
 * page can show the same refusal without importing this module. See
 * `packRelease` for what the guard is and what it is not.
 */
export function installRefusal(): string | null {
  return thisPackRelease().refusal
}

/**
 * This build's pinned release, judged from the constants THIS MODULE imports —
 * pack.ts `packRelease()` with them passed in rather than defaulted. The same
 * answer in production; the difference is that a test which swaps pack.ts's
 * release constants moves every screen that asks this, not only the client.
 */
export function thisPackRelease(): PackRelease {
  return packRelease({ published: PACK_PUBLISHED, sha256: PACK_SHA256, version: PACK_VERSION })
}

/** Read back what an install or upgrade left: the pack list says `version`,
 *  names `PACK_URL` as the source, and the pack's Raw HTTP source exists.
 *  Exported for packUpgrade.ts. */
export async function verifyInstalled(group: string, version: string): Promise<PackStep> {
  const found = await readInstalled(group)
  if ('error' in found) return { key: 'verify', action: 'error', detail: `could not check the install: ${found.error}` }
  if (!found.pack) return { key: 'verify', action: 'error', detail: `${PACK_ID} is not in the group’s pack list after the install` }
  if (found.pack.version !== version) {
    return { key: 'verify', action: 'error', detail: `${PACK_ID} reports version ${found.pack.version ?? 'none'}, not ${version}` }
  }
  if (found.pack.source !== PACK_URL) {
    return {
      key: 'verify', action: 'error',
      detail: `${PACK_ID} ${version} is installed, but the group’s pack list does not name its release as the pack’s source, ` +
        'so this app cannot recognise the copy as its own to upgrade or remove it later',
    }
  }
  const input = await capi('GET', packPath(group, `/system/inputs/${PACK_HTTP_INPUT_ID}`))
  if (input.status !== 200 || !firstItem(input)) {
    return { key: 'verify', action: 'error', detail: `${PACK_ID} ${version} is installed, but its source ${PACK_HTTP_INPUT_ID} could not be read (HTTP ${input.status})` }
  }
  return { key: 'verify', action: 'exists', detail: `${PACK_ID} ${version} · ${PACK_HTTP_INPUT_ID} present` }
}

/** Install `PACK_VERSION` from `PACK_URL` into `group`, then read it back.
 *  Refuses when the pack is already there: that is `upgradePack`'s job. */
export async function installPack(group: string): Promise<PackStep[]> {
  const refusal = installRefusal()
  if (refusal) return [{ key: 'pack', action: 'skipped', detail: refusal }]
  const found = await readInstalled(group)
  if ('error' in found) return [{ key: 'pack', action: 'error', detail: found.error }]
  if (found.pack) {
    const at = found.pack.version ? ` ${found.pack.version}` : ''
    return [{ key: 'pack', action: 'error', detail: `${PACK_ID}${at} is already installed in ${group} — upgrade it instead` }]
  }
  const r = await capi('POST', groupPath(group, '/packs'), { id: PACK_ID, source: PACK_URL, allowCustomFunctions: false })
  if (r.status < 200 || r.status >= 300) return [{ key: 'pack', action: 'error', detail: scrubbedErrText(r, []) }]
  return [{ key: 'pack', action: 'created', detail: `${PACK_ID} ${PACK_VERSION}` }, await verifyInstalled(group, PACK_VERSION)]
}

/**
 * Uninstall the pack — only a copy that is this app's by both signals: a
 * version this app published, installed from that version's release. The Lake
 * datasets it writes to are outside the pack and are left alone.
 */
export async function removePack(group: string): Promise<PackStep> {
  const found = await readInstalled(group)
  if ('error' in found) return { key: 'pack', action: 'error', detail: `kept — ${found.error}` }
  if (!found.pack) return { key: 'pack', action: 'exists', detail: 'not present' }
  const kept = notOurs(found.pack)
  if (kept) return { key: 'pack', action: 'error', detail: kept }
  const r = await capi('DELETE', groupPath(group, `/packs/${PACK_ID}`))
  if (r.status === 404) return { key: 'pack', action: 'exists', detail: 'not present' }
  if (r.status < 200 || r.status >= 300) return { key: 'pack', action: 'error', detail: scrubbedErrText(r, []) }
  return { key: 'pack', action: 'updated', detail: 'deleted' }
}

// ── The pack's two sources ──────────────────────────────────────────────────

type Which = 'http' | 'sample'

/** What an edit of a live source decided: the keys to set, or why not. */
type Edit = { set: Record<string, unknown> } | { refuse: string }

/** One change to one of the pack's sources, decided against the live object. */
interface Plan {
  which: Which
  edit: (live: Record<string, unknown>) => Edit
  /** Scrubbed from any error, beside every token the live source holds. */
  secrets: readonly string[]
}

/** A change to one of the pack's sources, as the UI names it. */
export type PackInputChange =
  /** Everything an install sets on the Raw HTTP source, in one PATCH. */
  | { kind: 'configure'; port: number; token: string; hosting: Hosting }
  /** Move the Raw HTTP source to another port. */
  | { kind: 'port'; port: number; hosting: Hosting }
  /** Replace the Raw HTTP source's auth token (a rotation). */
  | { kind: 'token'; token: string }
  /** Start the Raw HTTP source. */
  | { kind: 'enable'; hosting: Hosting }
  /** Start or stop the sample DataGen. */
  | { kind: 'sample'; enabled: boolean }

/** What a confirmation shows before a source change is sent, or the step the
 *  write itself would return instead. An empty diff is "nothing changes". */
export type PackInputPreview =
  | { ok: true; key: PackStepKey; diff: DiffRow[] }
  | { ok: false; step: PackStep }

const inputKey = (which: Which): PackStepKey => (which === 'http' ? 'http_input' : 'sample_input')

/** A token this app would have generated: at least 128 bits, as hex. The
 *  refusal never repeats what it was given. */
const TOKEN_SHAPE = /^[0-9a-f]{32,}$/i
const BAD_TOKEN = 'not applied — the token must be at least 128 bits of hex, as generateToken makes it'
const NO_HOSTING = 'not applied — this app cannot tell whether the group is Cribl-managed or hybrid, which decides the port range and TLS'

/** The pack's Raw HTTP source's TLS as the pack ships it: Cribl.Cloud's own
 *  certificate. pack.test.ts holds inputs.yml's `tls` equal to `tlsFor(true)`. */
const SHIPPED_TLS = tlsFor(true)

/**
 * The `tls` block to set on the Raw HTTP source, or null to leave the live one.
 *
 * A TLS BLOCK THE SOURCE ALREADY HAS IS SOMEBODY'S DECISION, and is kept: a
 * certificate added to a hybrid group after the install, or a managed group's
 * own certificate. Overwriting it with `tlsFor(hosting)` put a hybrid group
 * back on plaintext on the next enable. Two cases are set:
 *   * no TLS block at all — TLS for the group's hosting;
 *   * a hybrid group still on the pack's shipped block, which names
 *     `$CRIBL_CLOUD_CRT`, a certificate that does not exist there (the source
 *     would never start) — TLS off, which the endpoint card says plainly.
 */
function tlsToSet(live: Record<string, unknown>, hosting: 'managed' | 'hybrid'): Record<string, unknown> | null {
  const tls = live.tls
  if (!tls || typeof tls !== 'object' || Array.isArray(tls)) return tlsFor(hosting === 'managed')
  if (hosting === 'hybrid' && sameValue(tls, SHIPPED_TLS)) return tlsFor(false)
  return null
}

/** The ports every other source in the group listens on — its own, and other
 *  packs' — or null when any could not be read ("cannot tell" is never "free"). */
export async function portsOfOthers(group: string): Promise<number[] | null> {
  const inputs = await groupInputs(group)
  if (!inputs) return null
  return portsInUse(inputs.filter((i) => !(i.pack === PACK_ID && i.id === PACK_HTTP_INPUT_ID)))
}

/** Why an enabled source here would be unsafe, or null. */
function enableProblem(live: Record<string, unknown>, hosting: 'managed' | 'hybrid', used: number[] | null): string | null {
  if (tokensOf(live).length === 0) {
    return 'not enabled — the source has no auth token, so it would accept a POST from anyone who can reach the port'
  }
  const port = numberOr(live.port)
  if (port === null) return 'not enabled — this app cannot read the source’s port'
  const problem = portProblem(port, hosting === 'managed', used)
  return problem ? `not enabled — port ${port}: ${problem}` : null
}

/** The change as a plan against the live source, or the refusal that needs no
 *  read of it. Reads the group's ports, or Lake's datasets, where the change
 *  depends on them — GETs only. */
async function planFor(group: string, change: PackInputChange): Promise<Plan | PackStep> {
  const refuse = (detail: string): PackStep => ({ key: change.kind === 'sample' ? 'sample_input' : 'http_input', action: 'error', detail })
  switch (change.kind) {
    case 'configure': {
      const { port, token, hosting } = change
      if (!hosting) return refuse(NO_HOSTING)
      if (!TOKEN_SHAPE.test(token)) return refuse(BAD_TOKEN)
      const problem = portProblem(port, hosting === 'managed', await portsOfOthers(group))
      if (problem) return refuse(`not applied — port ${port}: ${problem}`)
      return {
        which: 'http',
        edit: (live) => {
          const tls = tlsToSet(live, hosting)
          return { set: { port, ...(tls ? { tls } : {}), authTokensExt: [{ token, authType: 'manual' }], disabled: false } }
        },
        secrets: [token],
      }
    }
    case 'port': {
      const { port, hosting } = change
      if (!hosting) return refuse(NO_HOSTING)
      const problem = portProblem(port, hosting === 'managed', await portsOfOthers(group))
      if (problem) return refuse(`not applied — port ${port}: ${problem}`)
      return { which: 'http', edit: () => ({ set: { port } }), secrets: [] }
    }
    case 'token': {
      const { token } = change
      if (!TOKEN_SHAPE.test(token)) return refuse(BAD_TOKEN)
      return { which: 'http', edit: () => ({ set: { authTokensExt: [{ token, authType: 'manual' }] } }), secrets: [token] }
    }
    case 'enable': {
      const { hosting } = change
      if (!hosting) return refuse(NO_HOSTING)
      const used = await portsOfOthers(group)
      return {
        which: 'http',
        edit: (live) => {
          const problem = enableProblem(live, hosting, used)
          if (problem) return { refuse: problem }
          const tls = tlsToSet(live, hosting)
          return { set: { disabled: false, ...(tls ? { tls } : {}) } }
        },
        secrets: [],
      }
    }
    case 'sample': {
      if (change.enabled) {
        const datasets = await listDatasets()
        if (datasets.outcome !== 'ok') {
          return refuse(`not started — Cribl Lake’s dataset list could not be read, so this app cannot check ${PACK_SAMPLE_DATASET_ID} exists`)
        }
        if (!(datasets.value ?? []).some((d) => d.id === PACK_SAMPLE_DATASET_ID)) {
          return refuse(`not started — the ${PACK_SAMPLE_DATASET_ID} dataset does not exist yet`)
        }
      }
      return { which: 'sample', edit: () => ({ set: { disabled: !change.enabled } }), secrets: [] }
    }
  }
}

/** Read one of the pack's sources whole. Two literal paths, not one built from
 *  `which`, so policyCoverage.test.ts can read each call site. */
async function readLive(group: string, which: Which) {
  return which === 'http'
    ? capi('GET', packPath(group, `/system/inputs/${PACK_HTTP_INPUT_ID}`))
    : capi('GET', packPath(group, `/system/inputs/${PACK_SAMPLE_INPUT_ID}`))
}

/**
 * The before→after of setting `set` on `live`, key by key and sorted, for
 * `<ConfirmDialog diff>`. A key the change leaves as it is gives no row. Token
 * values never appear: `authTokensExt` reads "a token is set (not shown)" →
 * "a new token (not shown)".
 */
function diffOf(live: Record<string, unknown>, set: Record<string, unknown>): DiffRow[] {
  const rows: DiffRow[] = []
  for (const key of Object.keys(set).sort()) {
    const after = set[key]
    const had = Object.hasOwn(live, key) && live[key] !== undefined
    if (had && sameValue(live[key], after)) continue
    if (key === 'authTokensExt') {
      rows.push({
        key, kind: had ? 'changed' : 'added',
        before: had ? (tokensOf({ authTokensExt: live[key] }).length ? 'a token is set (not shown)' : 'no token') : undefined,
        after: 'a new token (not shown)',
      })
      continue
    }
    rows.push({ key, kind: had ? 'changed' : 'added', before: had ? live[key] : undefined, after })
  }
  return rows
}

/** Read the live source and decide the change against it: what to set, its
 *  diff and what to scrub — or the step that ends it without a write. */
async function decide(
  group: string,
  plan: Plan,
): Promise<{ live: Record<string, unknown>; set: Record<string, unknown>; diff: DiffRow[]; scrub: string[] } | { step: PackStep }> {
  const key = inputKey(plan.which)
  const id = plan.which === 'http' ? PACK_HTTP_INPUT_ID : PACK_SAMPLE_INPUT_ID
  const got = await readLive(group, plan.which)
  if (got.status === 404) return { step: { key, action: 'error', detail: `${id} is not in ${PACK_ID} here — is the pack installed?` } }
  const live = got.status === 200 ? firstItem(got) : null
  if (!live) {
    return {
      step: {
        key, action: 'error',
        detail: got.status === 200
          ? `not applied — this app could not read the live ${id}, and this endpoint replaces the whole object`
          : scrubbedErrText(got, plan.secrets),
      },
    }
  }
  const decided = plan.edit(live)
  if ('refuse' in decided) return { step: { key, action: 'error', detail: decided.refuse } }
  return { live, set: decided.set, diff: diffOf(live, decided.set), scrub: [...tokensOf(live), ...plan.secrets] }
}

/**
 * GET → overlay → PATCH the whole body of one of the pack's sources. The
 * endpoint is a full replacement (openapi.json, and measured on the group's own
 * sources), so the body is the live object with only the plan's keys changed
 * and the server-owned keys left out. Nothing is sent when nothing would
 * change, and nothing when `approved` (the diff a confirmation showed) is not
 * the diff this read gives: the source moved after it was shown.
 */
async function patchPackInput(group: string, plan: Plan, approved?: readonly DiffRow[]): Promise<PackStep> {
  const key = inputKey(plan.which)
  const d = await decide(group, plan)
  if ('step' in d) return d.step
  if (approved !== undefined && !sameDiff(approved, d.diff)) {
    if (d.diff.length === 0) return { key, action: 'exists', detail: 'nothing left to change — it was applied after this change was shown' }
    return {
      key, action: 'error',
      detail: `not applied — the source changed after this change was shown, so what was confirmed is not what would now be sent. ` +
        `Would now change: ${d.diff.map((r) => r.key).join(', ') || 'nothing'}. Look again, and confirm again.`,
    }
  }
  if (d.diff.length === 0) return { key, action: 'exists', detail: 'already set' }
  const body: Record<string, unknown> = { ...d.live }
  for (const k of SOURCE_SERVER_OWNED) delete body[k]
  Object.assign(body, d.set)
  const r = plan.which === 'http'
    ? await capi('PATCH', packPath(group, `/system/inputs/${PACK_HTTP_INPUT_ID}`), body)
    : await capi('PATCH', packPath(group, `/system/inputs/${PACK_SAMPLE_INPUT_ID}`), body)
  if (r.status < 200 || r.status >= 300) return { key, action: 'error', detail: scrubbedErrText(r, d.scrub), sent: true }
  return { key, action: 'updated', detail: d.diff.map((row) => row.key).join(', ') }
}

/**
 * What `applyPackInput(group, change)` would change, read and decided exactly
 * as it will be — GETs only, nothing written. Pass the diff to
 * `<ConfirmDialog diff>`, and the same diff back as `approved` once confirmed.
 */
export async function previewPackInput(group: string, change: PackInputChange): Promise<PackInputPreview> {
  const plan = await planFor(group, change)
  if (!('which' in plan)) return { ok: false, step: plan }
  const d = await decide(group, plan)
  if ('step' in d) return { ok: false, step: d.step }
  return { ok: true, key: inputKey(plan.which), diff: d.diff }
}

/**
 * Make one change to one of the pack's sources. With `approved` (the diff a
 * confirmation showed, from `previewPackInput`), nothing is sent unless the
 * live source still gives exactly that diff.
 */
export async function applyPackInput(group: string, change: PackInputChange, approved?: readonly DiffRow[]): Promise<PackStep> {
  const plan = await planFor(group, change)
  if (!('which' in plan)) return plan
  return patchPackInput(group, plan, approved)
}

/**
 * Everything an install has to set on the pack's Raw HTTP source, in ONE
 * whole-body PATCH: a free port for the group's hosting, the new token, TLS for
 * the hosting where the source has none of its own (`tlsToSet`), and enabled.
 * This is the call the Guided Setup slice makes after an install.
 */
export function configureHttpInput(
  group: string,
  opts: { port: number; token: string; hosting: Hosting },
  approved?: readonly DiffRow[],
): Promise<PackStep> {
  return applyPackInput(group, { kind: 'configure', ...opts }, approved)
}

/** Move the pack's Raw HTTP source to another port, checked free and inside
 *  what the group's hosting allows. */
export function setSourcePort(group: string, port: number, hosting: Hosting, approved?: readonly DiffRow[]): Promise<PackStep> {
  return applyPackInput(group, { kind: 'port', port, hosting }, approved)
}

/** Replace the pack's Raw HTTP source's auth token (a rotation). The old one
 *  stops working at the next deploy. */
export function setHttpToken(group: string, token: string, approved?: readonly DiffRow[]): Promise<PackStep> {
  return applyPackInput(group, { kind: 'token', token }, approved)
}

/** Start the pack's Raw HTTP source: `disabled` only, plus TLS where the
 *  source has none of its own (`tlsToSet`). Refused while it has no token or
 *  its port is not usable. */
export function enableHttpInput(group: string, hosting: Hosting, approved?: readonly DiffRow[]): Promise<PackStep> {
  return applyPackInput(group, { kind: 'enable', hosting }, approved)
}

/**
 * Start or stop the sample DataGen. Starting it is refused until its own
 * dataset, `gigamon_ami_sample`, exists: the pack cannot create a dataset, and
 * a destination with nowhere to write blocks.
 */
export function setSampleEnabled(group: string, enabled: boolean, approved?: readonly DiffRow[]): Promise<PackStep> {
  return applyPackInput(group, { kind: 'sample', enabled }, approved)
}

// ── Committing the pack's files ─────────────────────────────────────────────

/**
 * What selects this pack's files among a group's pending Git paths: any path
 * with a segment named exactly after the pack. MEASURED: an install lands
 * under `groups/<g>/default/<pack>/` and `groups/<g>/data/packs/<pack>/`; both
 * hold this segment, and so would any other directory Cribl names after the
 * pack (where a PATCH of a pack source lands is not measured). A sibling pack
 * whose id merely starts with this one's does not match: the segment is
 * slash-delimited on both sides.
 */
export const PACK_COMMIT_MARKERS: readonly string[] = Object.freeze([`/${PACK_ID}/`])

/** The two measured directories, as the commit names them when Git reports
 *  nothing pending at all (provision.ts's fallback). */
export const packCommitPaths = (group: string): string[] => [
  `groups/${group}/default/${PACK_ID}`,
  `groups/${group}/data/packs/${PACK_ID}`,
]

/**
 * The key a pack commit's hash is kept under in Guided Setup's commit memory
 * (setupMemory.ts: group → key → {hash, message}). Not a `ResourceKey`: the
 * pack is not one of the stack's rows. provision.ts's stranded-commit repair
 * reads every key of the group, so a hash here is one it will deploy.
 */
export const PACK_COMMIT_KEY = 'onboarding_pack'

/** What a commit of the pack's files in `group` carries, and what else is
 *  pending — the two things its confirmation has to say (provision.ts
 *  `commitScopeFor`). Pure: `pending` is `pendingConfigPaths()`. */
export function packCommitScope(group: string, pending: readonly string[] | null): CommitScope {
  return commitScopeFor(group, packCommitPaths(group), PACK_COMMIT_MARKERS, pending)
}

export interface PackCommitOptions {
  /**
   * Whether this run's pack write changed something (an install, upgrade or
   * remove that succeeded, or a source change that answered `updated`). After
   * one, finding nothing of the pack's to commit is an ERROR — the change would
   * never be committed or deployed — rather than "up to date".
   */
  wrote: boolean
  /**
   * Record a pack commit's hash in Guided Setup's commit memory under
   * `(group, PACK_COMMIT_KEY)`: ProvisionPanel's `recordCommit`, bound. Called
   * as soon as the commit step carries a hash — before the deploy, and also
   * when the deploy then fails — and awaited before this returns. Without it,
   * the stranded-commit repair refuses the pack's commit as "not made by this
   * app" on every later run.
   */
  record: (hash: string, message: string) => Promise<unknown>
}

/** Commit exactly the pack's pending files in `group`, then deploy — Guided
 *  Setup's own machinery (provision.ts `commitMatchingAndDeploy`), not a copy. */
export async function commitAndDeployPack(
  group: string,
  message: string,
  opts: PackCommitOptions,
  onStep?: (r: StepResult) => void,
  onPhase?: OnPhase,
): Promise<StepResult[]> {
  let recorded: Promise<unknown> | null = null
  const step = (r: StepResult) => {
    const hash = r.key === 'commit' ? r.hash : undefined
    if (hash && !recorded) recorded = Promise.resolve().then(() => opts.record(hash, r.message ?? message)).catch(() => false)
    onStep?.(r)
  }
  const nothingCommitted = opts.wrote
    ? `the pack was changed, but Git reports none of its files uncommitted in ${group}, so none of its files were committed ` +
      `and nothing was deployed. Commit and deploy ${group} in Cribl.`
    : null
  const steps = await commitMatchingAndDeploy(message, group, PACK_COMMIT_MARKERS, packCommitPaths(group), step, onPhase, nothingCommitted)
  await recorded
  return steps
}
